.\" This file is part of the Lightweight Universal Network Analyzer (LUNA)
.\"
.\" Copyright (c) 2013 Fiona Klute
.\"
.\" LUNA is free software: you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" LUNA is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
.\" or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
.\" License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with LUNA. If not, see <http://www.gnu.org/licenses/>.

.TH LUNA 1 2013-11-04 "LUNA" "LUNA Manual"

.SH NAME
luna \- generate and record packets to measure network performance

.SH SYNOPSIS
.B luna
-s|-c SERVER [OPTIONS]...

.SH DESCRIPTION
.P
TODO
.SS Generators
.P
TODO

.SH OPTIONS

.TP
.B \-s
Run in server mode. \fB\-s\fR and \fB\-c\fR are mutually exclusive.

.TP
.B \-c SERVER
Run in client mode, send to the specified server. The server can be
given by hostname, IPv4 or IPv6 address. \fB\-c\fR and \fB\-s\fR are
mutually exclusive.

.TP
.B \-p PORT
Use the specified port. In server mode, \fBluna\fR binds this UDP
port for listening. In client mode, this is used as the destination
port.

.TP
.B \-4
Run in IPv4 only mode

.TP
.B \-6
Run in IPv6 only mode

.TP
.B \-T
Write tab separated output. This is required to use the analysis tools
provided by LUNA, and strongly recommended if you want to write your
own. May become default behavior in the future.

.TP
.B \-t SECONDS
Send for the given number of seconds (client mode only)

.TP
.B \-g GENERATOR
Use the named generator (client mode only). Default is "static".

.TP
.B \-a ARGS
Pass the specified arguments to the configured generator (see option
.BR \-g ).
Generator arguments must be written in the format
name=value,... Acceptable names and values depend on the generator.

.TP
.B \-e
Request echo packets for round trip time measurements (client mode only)

.TP
.B \-o FILE
Write recorded results to FILE instead of standard out

.SH EXIT STATUS
.P
.B 0
if execution completed normally, non-zero in case of an error. In the
latter case,
.BR luna
will output an error message for the user. Error exit codes are
defined in
.BR luna.h .

.SH ENVIRONMENT
.P
Generators using random generators from the GNU Scientific Library
(libgsl) may be influenced by the environment variables evaluated in
.BR gsl_rng_env_setup (),
see section "Random number environment variables" in the libgsl
handbook.

.SH NOTES
.P
TODO: PREEMPT_RT

.SH EXAMPLE
.P
TODO

.SH SEE ALSO
.P
TODO
